language: node_js
node_js:
  - "stable"
before_script: 
  - npm run createTable
script:
  - npm test
after_script: 
  - npm run dropTable
after_success:
  - npm run coverage
  - npm run report-coverage
env:
  global:
    - NODE_ENV = test