language: node_js
node_js:
  - "stable"
before_script:
  - npm run createTable
  - npm run createAdmin
  - npm install
  - npm i -D coveralls
script:
  - npm run coverage
after_script: 
  - npm run dropTable
after_success:
  - npm run report-coverage
env:
  - NODE_ENV = test
